version: '3.8'
services:
  app:
    build: .
    container_name: news-app
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/app
#      - /opt/app/node_modules
    depends_on:
      - postgres
    networks:
      - app-network
    command: npm run start:dev

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge