version: '3.8'
services:
  app:
    build: .
    container_name: news-api
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/app
    depends_on:
      - postgres
    networks:
      - app-network
    command: npm run start:dev

  postgres:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge